### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by guoyage** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#1]
When I run the train file, there is a **ValueError: too many values to unpack (expected 2)** error 
in the **_pred_masks, ca_act_reg = self.model(inp_imgs)_** statement.

I hope you can help. @sairajk

**Comment by sairajk** [comment]
Hi @guoyage, I am not getting this error. Can you give me some more information to reproduce it?

I suggest you decrease the batch size to 3 and run the train.py file as it is after cloning (without changing anything else, not even the dataset). See if there are any errors. Also, run the model.py file as `python model.py` and see if it generates an error.
