### ISSUE TITLE
Output images

### ISSUE THREAD

**Issue by mayuri2307** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#12]
Hi,
I am getting the output images as grayish images rather than black and white. Could you help me what's the problem and how to deal with it?

**Comment by sairajk** [comment]
Can you share some sample output images? And also what changes have you made before running the code?

**Comment by sairajk** [comment]
Closing the issue, feel free to reopen.

**Comment by peterwilson3912** [comment]
One thing that you might should nitice is that in interface.py file 
`# img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)`

This line might change color.
