### ISSUE TITLE
File name of the out put images

### ISSUE THREAD

**Issue by peterwilson3912** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#15]
Hi! I'm using this model on my own dataset. I met the problem of the order of the image. 
I basically run `interface.py` to get my output. 

The input folder of my file looks like this:
![image](https://user-images.githubusercontent.com/36145675/90931176-109f5d80-e3ca-11ea-9876-f735919c9d79.png)

The name is from 0 to 504.
But when the python program reads the file, it will reorder the image and disorganize the images. Windows usually read like 000, 001,002...100,101,102....

I notice that you use `InfDataloader`. But I'm wondering whether I can use some API to get the name.  save it like line 68-76:
![image](https://user-images.githubusercontent.com/36145675/90931537-da161280-e3ca-11ea-9630-75aa35f9f98a.png)

The result image that I got doesn't have the same order as my input. For example, input 0.png is output 187.png.

I'm wondering how to keep the order and file name as the input. Would you please help me with this?
I'm not familiar with pytorch.

Thank you so so so much!!!!!!!

**Comment by mushroompyq** [comment]
@karliell Do you solve the problem？I also want to know how to deal with it.I‘m looking forward to recieving your replay，thank you.

**Comment by karliell** [comment]
Yes. I modified some code. You may send me your email and I can send you the code.

**Comment by peterwilson3912** [comment]
> @karliell Do you solve the problem？I also want to know how to deal with it.I‘m looking forward to recieving your replay，thank you.

Yes. I modified some code. You may send me your email and I can send you the code.

**Comment by mushroompyq** [comment]
> > @karliell Do you solve the problem？I also want to know how to deal with it.I‘m looking forward to recieving your replay，thank you.
> 
> Yes. I modified some code. You may send me your email and I can send you the code.

Thank you very much.My email is 1185531636@qq.com.

**Comment by sairajk** [comment]
The best way would be to return the image path along with `img_np` and `img_tor` in the `InfDataloader` like `return self.img_paths[idx], img_np, img_tor` and then use the input image path as a reference in `run_inference` to save your output image.
