### ISSUE TITLE
Detailed questions

### ISSUE THREAD

**Issue by peterwilson3912** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#16]
Hi! I'm wondering the meaning of this 
https://github.com/sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/blob/master/inference.py#L52

What is `img_np` and `mg_tor`?

Why do you put  `img_tor` into the model?

Thanks a lot!!!!!!

**Comment by sairajk** [comment]
`img_np` is a NumPy (`numpy.array`) image and `img_tor` is the pre-processed image as Torch tensor which is used as input to the model.
