### ISSUE TITLE
Implementation different from the paper

### ISSUE THREAD

**Issue by clelouch** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#18]
Thanks for your code! 
After reading your code and the paper, I found some differece.
![image](https://user-images.githubusercontent.com/33519394/92471896-45554680-f20b-11ea-9493-d11e0c0df062.png)
![image](https://user-images.githubusercontent.com/33519394/92471912-4be3be00-f20b-11ea-80ca-a49a2e868643.png)
In your code, the SA module process the conv_345_feats. However, in the original paper, the SA module process low-level features. @sairajk

**Comment by sairajk** [comment]
Hi @clelouch, I know. I followed the official implementation provided by the authors [here](https://github.com/CaitinZhao/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection)
