### ISSUE TITLE
Question about RetinaNet FPN implementation

### ISSUE THREAD

**Issue by alancarlosml** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#19]
Hello,

I am working with image detection tasks with RetinaNet.

I would like to know if is possible join this fpn implementation with RetinaNet.

Basically I want train this FPN implementation with my train dataset, save the weights and use them to detect the objects in my test dataset.

**Comment by sairajk** [comment]
Yes, you can use this FPN as a feature extractor for detection.
