### ISSUE TITLE
Error while using Google Colab

### ISSUE THREAD

**Issue by IzabelaKrupinska** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#2]
ValueError                                Traceback (most recent call last)

<ipython-input-33-a4b16b758554> in <module>()
    228     test_data = SODLoader(mode='test', augment_data=False, target_size=img_size)
    229 
--> 230     train_dataloader = DataLoader(train_data, batch_size=bs, shuffle=True, num_workers=1)
    231     test_dataloader = DataLoader(test_data, batch_size=bs, shuffle=False, num_workers=2)
    232 

92         if not isinstance(self.num_samples, int) or self.num_samples <= 0:
     93             raise ValueError("num_samples should be a positive integer "
---> 94                              "value, but got num_samples={}".format(self.num_samples))
     95 
     96     @property

ValueError: num_samples should be a positive integer value, but got num_samples=0

What should I do with that?

**Comment by Nida-Fatima** [comment]
Hi! have you resolved this error? I am encountering the same error.
