### ISSUE TITLE
How can I  save the mask image of test?

### ISSUE THREAD

**Issue by hufeng0912** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#20]
I can't see any save path of the mask image in your code

**Comment by SohailKumar** [comment]
> I can't see any save path of the mask image in your code

Did you find a solution to this?

**Comment by sairajk** [comment]
The saliency mask generated for the inference image is not saved, it is just displayed on the screen (see [line](https://github.com/sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/blob/074722ea2b52d6dbcb581e2477813ce2e87e3bca/inference.py#L63)). However, you can add your own code to save the mask.
