### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by IzabelaKrupinska** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#3]
Is it possible to provide Your pre-trained model? "best_epoch-138_acc-0.9107_loss-0.1300.pt"
Did You trained it on DUTS-TR?

**Comment by sairajk** [comment]
Hi @IzabelaKrupinska, I have been busy quite some time. I will try to upload them by the next week. And yes, I trained it on the DUTS-TR dataset.

**Comment by IzabelaKrupinska** [comment]
Thank You very much for fast reply 😊 I am training the network too but I am waiting for yours model to compare them and check 😊

Best wishes,

Z poważaniem,
Izabela Krupińska

Od: Sai Raj Kishore
Wysłano: piątek, 29 listopada 2019 19:01
Do: sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection
DW: IzabelaKrupinska; Mention
Temat: Re:[sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection]Pre-trained model (#3)

Hi @IzabelaKrupinska, I have been busy quite some time. I will try to upload them by the next week. And yes, I trained it on the DUTS-TR dataset.

**Comment by creabob** [comment]
hello ,hava u provided your pre-trained model?

**Comment by creabob** [comment]
> Hi @IzabelaKrupinska, I have been busy quite some time. I will try to upload them by the next week. And yes, I trained it on the DUTS-TR dataset.

waiting for your pre-trained model ,and thank u for your work

**Comment by dragen1860** [comment]
Hi, looking forward to the pretrained model!!!

**Comment by dragen1860** [comment]
@sairajk

**Comment by xuexuetong1993** [comment]
Hi, looking forward to the pretrained model!!!
@sairajk

**Comment by woojaekim** [comment]
Hi, Im looking forward to the pre-trained model
@sairajk

**Comment by sairajk** [comment]
Hi all, the pre-trained weights (trained on DUTS-TR) are now made available.

@IzabelaKrupinska @creabob @dragen1860 @xuexuetong1993 @woojaekim

**Comment by woojaekim** [comment]
Many Thanks! @sairajk

**Comment by mayuri2307** [comment]
> Hi all, the pre-trained weights (trained on DUTS-TR) are now made available.
> 
> @IzabelaKrupinska @creabob @dragen1860 @xuexuetong1993 @woojaekim

could you let me know where it is? while running train.py, I am having the issue that
'./models/alph-0.7_wbce_w0-1.0_w1-1.15weights/best_epoch-000_mae-0.5193_loss-1.0834.pth"
How can I resolve this?
