### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by taxuewuhenxiaoer** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#6]
when i run the train.py code, i have a error like this:
ValueError: num_samples should be a positive integer value, but got num_samples=0  
why ?

**Comment by sairajk** [comment]
Can you give me some more details, like the error traceback or any changes that you made to the code before running.

Also, I would ask you to just clone the repository and run the code as it is first. See if you get any errors.
