### ISSUE TITLE
how to see all test image results after run the inference.py?

### ISSUE THREAD

**Issue by lj107024** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#7]

**Comment by lj107024** [comment]
thanks! I have got it. However, I meet another question, the ouput images Rounded-off Saliency Mask looks much better than Generated Saliency Mask , which is the real result of this method?
`        for batch_idx, (img_np, img_tor) in enumerate(inf_dataloader, start=1):
            img_tor = img_tor.to(device)
            pred_masks, _ = model(img_tor)

            # Assuming batch_size = 1
            img_np = np.squeeze(img_np.numpy(), axis=0)
            img_np = img_np.astype(np.uint8)
            img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
            pred_masks_raw = np.squeeze(pred_masks.cpu().numpy(), axis=(0, 1))
            pred_masks_round = np.squeeze(pred_masks.round().cpu().numpy(), axis=(0, 1)

            print('Image :', batch_idx)
            cv2.imshow('Input Image', img_np)
            cv2.imshow('Generated Saliency Mask', pred_masks_raw)
            cv2.imshow('Rounded-off Saliency Mask', pred_masks_round)`

**Comment by sairajk** [comment]
In the raw saliency mask pixel values are between 0 and 1 (this is the output directly from the model), while in the rounded off saliency mask the pixel values are either 0 or 1. The later one looks better as some of the surrounding noise is removed and the resultant mask is much sharper.
